### ISSUE TITLE
我集成到spring项目中报这个错误, 文件是在resource下的

### ISSUE THREAD

**Issue by JxJPu9bD** [TencentCloud/ckafka-sdk-demo#21]
直接run是没有问题的, package的jar 在Windows下使用

java -jar *.jar 也可以正常启动, 
但是jar放到MacOS和 linux下启动就会报这个错误

`
Caused by: java.lang.SecurityException: java.io.IOException: src/main/resources/ckafka_client_jaas.conf (No such file or directory)
        at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:139)
        at java.base/sun.security.provider.ConfigFile.<init>(ConfigFile.java:104)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
        at java.base/java.lang.Class.newInstance(Class.java:645)
        at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:258)
        at java.base/javax.security.auth.login.Configuration$2.run(Configuration.java:249)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
        at java.base/javax.security.auth.login.Configuration.getConfiguration(Configuration.java:248)
        at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:131)
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:103)
        at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:87)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:167)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:737)
        ... 37 common frames omitted
Caused by: java.io.IOException: src/main/resources/ckafka_client_jaas.conf (No such file or directory)
        at java.base/sun.security.provider.ConfigFile$Spi.ioException(ConfigFile.java:669)
        at java.base/sun.security.provider.ConfigFile$Spi.init(ConfigFile.java:265)
        at java.base/sun.security.provider.ConfigFile$Spi.<init>(ConfigFile.java:137)
        ... 56 common frames omitted
`

**Comment by JxJPu9bD** [comment]
java.io.IOException: src/main/resources/ckafka_client_jaas.conf (No such file or directory)

**Comment by JxJPu9bD** [comment]
这是一个kafka的问题, 我转移到其他机器是使用的路径, src必然不存在

有两种方法, 
1. java -jar -Djava.security.auth.login.config 来指定路径, 
2. 修改 kafka.properties 中的路径为 `java.security.auth.login.config=classpath:ckafka_client_jaas.conf`
这样类似使用相对路径, 但是直接package会报错, 需要跳过 test

我使用了第二种方法

**Comment by geniusjoe** [comment]
> java.io.IOException: src/main/resources/ckafka_client_jaas.conf (No such file or directory)

如果是 idea 的话，此处需要使用 demo 根目录对应的 pom.xml 打开项目。此处的报错应该是使用相对路径，找不到 jaas.conf 文件

**Comment by JxJPu9bD** [comment]
> > java.io.IOException: src/main/resources/ckafka_client_jaas.conf (No such file or directory)
> 
> 如果是 idea 的话，此处需要使用 demo 根目录对应的 pom.xml 打开项目。此处的报错应该是使用相对路径，找不到 jaas.conf 文件

嗯嗯, 感谢, 目前问题已经解决
